### ISSUE TITLE
Directors pages: videos not showing up on the right directors pages

### ISSUE THREAD

**Issue by thechrissie** [lubes/melvil#6]
Looks like all of the videos are showing up on this page[http://melvil.esw.me/film_directors/laurent-barthelemy/](url) regardless of which director is selected under project. 

eg. i assigned project "people inspire" to Chris Sargent but [his page](http://melvil.esw.me/film_directors/chris-sargent/) is blank

**Comment by lubes** [comment]
@thechrissie think you created a duplicate of that director.

**Comment by thechrissie** [comment]
i added a project called exobiotanica where "n/a" is the director. It's still showing up as chris sargeant which is the default selection.

**Comment by lubes** [comment]
Fixed
